server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msregister
    username: root
    password: 10391039
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
